### ISSUE TITLE
Vote & Watch

### ISSUE THREAD

**Issue by mauriciabad** [mauriciabad/ASW#13]
Vote/UnVote/Watch/UnWatch: 10%

**Comment by raimonmerce** [comment]
https://github.com/ryanto/acts_as_votable

**Comment by tataslas** [comment]
He creado una tabla en la db para poder guardar la gente que ve cada issue, usala cuando implementes esta funcionalidad

**Comment by raimonmerce** [comment]
Completados, tanto el ojo como las funcionalidades en show
