### ISSUE TITLE
Log In

### ISSUE THREAD

**Issue by mauriciabad** [mauriciabad/ASW#14]
Registre/login d'usuaris: 20%

**Comment by mauriciabad** [comment]
Hem de crear el Registre/login d'usuaris:
-Crear la Vista
-Modificar els controlers, en funcio del usuari
-Mirar d'utilitzar compte Google
https://richonrails.com/articles/google-authentication-in-ruby-on-rails

**Comment by raimonmerce** [comment]
Fet i comletat
